<template>
    <div class="ad-carousel">
        <div class="ad-carousel__inner">
            <div class="ad-carousel__item">
                <img />
            </div>
        </div>
        
    </div>
</template>

<script>
    export default {
        name: "ad-carousel"
        data: () => ({
            slides: [
                "https://picsum.photos/seed/picsum/200/300"
            ]
        })
    }
</script>

 <style lang="css" scoped>
    


</style>